#!/usr/bin/env python3
"""Build Matrix static command library.

Reads packs/*.json, normalizes placeholders, removes duplicate commands,
writes src/data.js, dist/commands.csv, and dist/stats.json.
"""
from __future__ import annotations
import csv
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACK_DIR = ROOT / "packs"
SRC_DIR = ROOT / "src"
DIST_DIR = ROOT / "dist"
PLACEHOLDER_ALIASES = {
    "ip": "IP",
    "rhost": "IP",
    "host": "IP",
    "target": "IP",
    "username": "USERNAME",
    "user": "USERNAME",
    "password": "PASSWORD",
    "pass": "PASSWORD",
    "domain": "DOMAIN",
    "lhost": "LHOST",
    "attacker_ip": "LHOST",
    "port": "PORT",
    "rport": "PORT",
    "token": "TOKEN",
    "user_id": "USER_ID",
    "userid": "USER_ID",
}
PH_RE = re.compile(r"\{\{\s*([A-Za-z0-9_ -]+)\s*\}\}")


def normalize_placeholders(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        raw = match.group(1).strip().replace("-", "_").replace(" ", "_")
        key = raw.lower()
        normalized = PLACEHOLDER_ALIASES.get(key, raw.upper())
        return "{{" + normalized + "}}"
    return PH_RE.sub(repl, text)


def placeholders_in(command: str) -> list[str]:
    return sorted(set(PH_RE.findall(command)))


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "command"


def load_pack(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError(f"{path} must contain a JSON list")
    return data


def main() -> None:
    SRC_DIR.mkdir(exist_ok=True)
    DIST_DIR.mkdir(exist_ok=True)
    commands = []
    seen = set()
    duplicates = []

    for pack in sorted(PACK_DIR.glob("*.json")):
        for item in load_pack(pack):
            required = ["section", "category", "title", "command", "description"]
            missing = [k for k in required if not item.get(k)]
            if missing:
                raise ValueError(f"{pack}: missing {missing} in {item}")

            command = normalize_placeholders(str(item["command"]).strip())
            dedupe_key = re.sub(r"\s+", " ", command).strip().lower()
            if dedupe_key in seen:
                duplicates.append(command)
                continue
            seen.add(dedupe_key)

            section = str(item["section"]).strip().title()
            category = str(item["category"]).strip()
            title = str(item["title"]).strip()
            commands.append({
                "id": f"{slugify(section)}-{slugify(category)}-{slugify(title)}",
                "section": section,
                "category": category,
                "title": title,
                "command": command,
                "description": str(item["description"]).strip(),
                "placeholders": placeholders_in(command),
                "pack": pack.stem,
            })

    commands.sort(key=lambda x: (x["section"], x["category"], x["title"]))

    data_js = "// Auto-generated by tools/build.py. Do not edit manually.\n"
    data_js += "window.MATRIX_COMMANDS = " + json.dumps(commands, indent=2) + ";\n"
    (SRC_DIR / "data.js").write_text(data_js, encoding="utf-8")

    with (DIST_DIR / "commands.csv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "section", "category", "title", "command", "description", "placeholders", "pack"])
        writer.writeheader()
        for c in commands:
            row = dict(c)
            row["placeholders"] = ",".join(c["placeholders"])
            writer.writerow(row)

    stats = {
        "total_commands": len(commands),
        "duplicates_removed": len(duplicates),
        "sections": Counter(c["section"] for c in commands),
        "categories_by_section": defaultdict(Counter),
        "placeholder_usage": Counter(p for c in commands for p in c["placeholders"]),
    }
    for c in commands:
        stats["categories_by_section"][c["section"]][c["category"]] += 1
    stats["sections"] = dict(stats["sections"])
    stats["categories_by_section"] = {k: dict(v) for k, v in stats["categories_by_section"].items()}
    stats["placeholder_usage"] = dict(stats["placeholder_usage"])
    (DIST_DIR / "stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

    print(f"Matrix build complete: {len(commands)} commands")
    print(f"Duplicates removed: {len(duplicates)}")
    print(f"Wrote: src/data.js, dist/commands.csv, dist/stats.json")


if __name__ == "__main__":
    main()
